keywords_list = [
    ["prompt injection"],
    ["prompt engineering"],
    ["few-shot prompt", "few shot prompt"],
    ["one-shot prompt", "one shot prompt"],
    ["few-shot prompting", "few shot prompting"],
    ["one-shot prompting", "one shot prompting"],
    ["prompting techniques"],
    ["prompt engineering techniques"],
    ["LLM prompting"],
    ["Large Language Model prompting"],
    ["zero-shot prompt"],
    ["many-shot prompt"],
    ["zero-shot prompting"],
    ["many-shot prompting"],
    ["in-context learning"],
    ["in context learning"],
    ["transformer model prompts"],
    ["prompt-based transfer learning"],
    ["NLP prompting strategies"],
    ["LLM interpretability via prompts"],
    ["curriculum learning with prompts"],
    ["feedback loops in LLM prompting"],
    ["human-in-the-loop prompting"],
    ["token-efficient prompting"],
    ["multimodal prompting"],
    ["instruction prompting"],
    ["Prompt Templating"],
    ["Prompt Template"],
]
