keywords_list = [
    ["prompt injection"],
    ["gpt-3", "gpt 3"],
    ["gpt-4", "gpt 4"],
    ["Auto-GPT", "Auto GPT"],
    ["prompt engineering"],
    ["few-shot", "few shot"],
    ["one-shot", "one shot"],
    ["prompting techniques"],
    ["LLM prompting"],
    ["zero-shot learning"],
    ["many-shot learning"],
    ["prompt design"],
    ["LLM instruction methods"],
    ["prompt optimization"],
    ["query reformulation for LLM"],
    ["contextual prompts"],
    ["dynamic prompting"],
    ["adaptive prompting"],
    ["fine-tuning"],
    ["transformer model prompts"],
    ["task-specific prompts"],
    ["natural language interface"],
    ["semantic prompting"],
    ["prompt-based transfer learning"],
    ["NLP prompting strategies"],
    ["LLM command formulation"],
    ["LLM user interfaces"],
    ["prompted model evaluation"],
    ["LLM task specification"],
    ["primer design for LLM"],
    ["LLM behavior shaping"],
    ["LLM interpretability via prompts"],
    ["curriculum learning with prompts"],
    ["feedback loops in LLM prompting"],
    ["active learning with prompts"],
    ["human-in-the-loop prompting"],
    ["token-efficient prompting"],
    ["multimodal prompting"],
    ["token manipulation"],
    ["hard prompts"],
    ["soft prompts"],
    ["cooperative prompting"],
    ["prompting"],
    ["Instruction Tuning"],
    ["Prompt Templating"],
    ["Dialog Systems"],
    ["Iterative Question Refinement"],
    ["Temperature Tuning"],
    ["Token Limiting"],
    ["Semantic Pivoting"],
    ["Meta-Learning", "Meta Learning"],
    ["Abstractive Summarization"],
    ["Answerability"],
    ["Knowledge Distillation"],
    ["Query Expansion"],
    ["Bias Reduction"],
    ["Knowledge Base"],
]
