keywords_list = [
    ["gpt-3", "gpt 3"],
    ["gpt-4", "gpt 4"],
    ["gpt 2, gpt-3"],
    ["chatgpt"],
    ["Auto-GPT", "Auto GPT"],
    ["PaLM 2"],
    ["llama 2"],
    ["llama-2"],
    ["google bard"],
    ["googles bard"],
    ["google's bard"],
    ["Claude AI"],
    ["Anthropic Claude"],
]
